### ISSUE TITLE
Watcher on title attribute

### ISSUE THREAD

**Issue by michelherv** [lordfriend/nya-bootstrap-select#105]
Can you add a watcher on title attribute ?

In my multilingual application, when I change language, the "title" attribute is updated but, the label in button is not. I think it need a simple watcher which will update the button label (if user haven't selected an option).

**Comment by lordfriend** [comment]
See #97 
You should use title-tpl attribute

**Comment by michelherv** [comment]
Hello, lordfriend, and thanks for your answer.

I have already try it, but it didn't work. I built  [this demo](http://plnkr.co/edit/5LHNSRcB9coGltqyR8sm?p=preview) to show what I'm talking about.

Sincerly.

**Comment by fromi** [comment]
This bug also apply to currently selected value. It does not refresh when I change the language.
I slightly changed your plunker to demonstrate this : http://plnkr.co/edit/jrydU6yG4pONiogvLuQA?p=preview
