### ISSUE TITLE
Slow performance with Angular 1.3.0

### ISSUE THREAD

**Issue by AaronJessen** [lordfriend/nya-bootstrap-select#11]
I tried implementing the nya-bootstrap-select with my Angular app (which is running 1.3.0-beta-16), and there appears to be a very big performance issue that affects any page where the widget is located. Any interaction with the user interface (typing, selecting from the dropdown) for controls bound with ng-model are very slow, even for those which aren't select pickers. Removing the nya-selectpicker class and reverting to the standard 'selectpicker' class fixes the problem. So, I'm led to believe that there is an issue which needs to be looked into.

**Comment by ImDineshSaini** [comment]
please share link of new version

**Comment by lordfriend** [comment]
@ImDineshSaini see release https://github.com/lordfriend/nya-bootstrap-select/releases
or using bower
