### ISSUE TITLE
Support data-thumbnail 

### ISSUE THREAD

**Issue by Sylistron** [lordfriend/nya-bootstrap-select#112]
http://thdoan.github.io/bootstrap-select/examples.html

Look for the section like: Select with Thumbnails

**Comment by lordfriend** [comment]
http://nya.io/nya-bootstrap-select/#!/examples/custom-content
I think there are no additional work to implement the feature. just as you can use a glyph icon in list element, you can use <img> tag as well.

**Comment by Sylistron** [comment]
Oh ok, I just have to do a bit more on my side, rather than using the data-thumbnail.  No worries.
