### ISSUE TITLE
In singleselect mode allow deselection

### ISSUE THREAD

**Issue by makkesk8** [lordfriend/nya-bootstrap-select#114]
Pretty much when not using "multiple" i want to be able to deselect current selected item by clicking on it again, Is there such support built in?

**Comment by lordfriend** [comment]
No such support, this is intentionally designed as single select should not deselect by the directive, you can deselect it with modify your model value.

**Comment by makkesk8** [comment]
right.. Well i will add it on my own then. Thank you.
