### ISSUE TITLE
Group by is ordering incorrectly

### ISSUE THREAD

**Issue by cash1981** [lordfriend/nya-bootstrap-select#115]
I have the following code

!`<ol class="nya-bs-select" ng-model="selectedTech.tech" data-live-search="true">
                <li nya-bs-option="tech in userCtrl.allAvailableTechs group by tech.tech.level">
                  <span class="dropdown-header">Level {{$group}}</span>
                  <a uib-tooltip="{{tech.tech.description}}">
                    <span>{{tech.tech.name}}</span>
                  </a>
                </li>
              </ol>`

It should group by "tech.tech.level"
However, it seems 3 and 4 comes before 2. So it groups by 1, 3, 4, 2 and 5
Very weird
This has worked previously, and I recon it has broken because of new angular-ui version.

![selection_006](https://cloud.githubusercontent.com/assets/404727/12702369/5e4ccdba-c827-11e5-9de7-b71f604e21ad.png)

Here is my bower.json

`"dependencies": {
    "lodash": "2.4.1",
    "angular": "~1.4.7",
    "json3": "~3.3.1",
    "es5-shim": "~3.1.0",
    "bootstrap": "3.3.1",
    "angular-resource": "~1.4.7",
    "angular-sanitize": "~1.4.7",
    "angular-animate": "~1.4.7",
    "angular-touch": "~1.4.7",
    "angular-route": "~1.4.7",
    "angular-utf8-base64": "~0.0.5",
    "angular-messages": "~1.4.7",
    "ng-table": "~0.3.3",
    "angular-bootstrap": "~0.14.3",
    "angular-growl-v2": "~0.7.5",
    "nya-bootstrap-select": "~2.1.3",
    "animate.css": "~3.2.6",
    "angularjs-scroll-glue": "~0.0.1",
    "angular-utils-pagination": "~0.9.2"
  }
![selection_006](https://cloud.githubusercontent.com/assets/404727/12702368/59f9ea5e-c827-11e5-89f1-ba6ef574bf14.png)
`

**Comment by lordfriend** [comment]
`nyaBsOption` directive won't reorder your collection when using group by. it just regroup the collection into known groups, this means if you have a element with a group `level 3` before the element with `level 2`, the final result will be group `level 3` before `level 2`

**Comment by cash1981** [comment]
I didn't understand what you meant.
So in short, I have to sort manually beforehand?

**Comment by lordfriend** [comment]
if you have an array like
```javascript
var list =  [{
  name: 'Alpha', 
  group: 'G1'
}, {
  name: 'Beta',
  group: 'G3'
}, {
  name: 'Charlie',
  group: 'G2'
}, {
  name: 'Delta',
  group: 'G2'
}, {
  name: 'Echo',
  group: 'G3'
}]
```

Then you will get the following result using `nya-bs-option="item in list group by item.group"` directive
```
---G1
|-- Alpha 
---G3
|-- Beta
|-- Echo
---G2
|-- Delta
```

**Comment by cash1981** [comment]
@lordfriend Thank you
Now I understood.
I will sort the array beforehand.

I will close this issue then since its my wrong understanding of group by
