### ISSUE TITLE
QUESTION : Async calls

### ISSUE THREAD

**Issue by kazoompa** [lordfriend/nya-bootstrap-select#116]
Hi,

Is there a way to call a user callback to retrieve data from server and populate the list? Similar to refresh callback of ui-select.

Thanks.

**Comment by lordfriend** [comment]
Sorry, this feature is not supported. You can use https://github.com/mbenford/ngTagsInput

**Comment by kazoompa** [comment]
May be in another release you can have callbacks that users can add to the directive for such use cases.

Thanks for the response.

**Comment by lordfriend** [comment]
Close: no roadmap to the feature
