### ISSUE TITLE
Custom content is not working

### ISSUE THREAD

**Issue by slavafomin** [lordfriend/nya-bootstrap-select#119]
Hello!

I'm trying to implement the button with custom content like in your example No. 2 here: http://nya.io/nya-bootstrap-select/#!/examples/custom-content with currency signs.

My code is looking like this:

```html
<ol ng-model="selectedCountry" class="nya-bs-select">
    <li
        nya-bs-option="country in countries"
        data-value="country.id"
        title="{~ country.title ~}"
    >
        <img ng-src="/images/country-flags/{~ country.isoCode ~}.png">
        {~ country.title ~}
    </li>
</ol>
```

I've tried different HTML constructs, but it didn't help. The resulting button (the box itself) contains only the title and not the image. However, list items are displayed correctly.

Please advise, thank you.

**Comment by lordfriend** [comment]
`<a>` is required as the child of `<li>` element, All custom content should put inside element `<a>`

**Comment by lordfriend** [comment]
Is this issue resolved?

**Comment by lordfriend** [comment]
Close due to no response and this is not a bug
