### ISSUE TITLE
all tests failing, build is broken

### ISSUE THREAD

**Issue by jpmckearin** [lordfriend/nya-bootstrap-select#121]
When attempting to build, all 13 tests fail with the following error:

 Error: [$injector:modulerr] Failed to instantiate module ng due to:
        TypeError: 'undefined' is not an object (evaluating 'Function.prototype.bind.apply')

**Comment by lordfriend** [comment]
Building on travis-ci are all passed. Would you please try to reinstall the dependencies?

**Comment by jpmckearin** [comment]
The latest ci build was over a month ago. A current build is now failing. It looks like there's an issue with the dependencies.

https://github.com/lordfriend/nya-bootstrap-select/pull/122

**Comment by jpmckearin** [comment]
Looking at the builds, your last one was on Jan. 30. On Feb. 5, angular 1.5.0 was released.

**Comment by jpmckearin** [comment]
I have verified that resolving dependencies to angular 1.4.9 fixes the build, so there is a change in 1.5.0 that is causing the failure.

**Comment by jpmckearin** [comment]
Seems to be a compatability issue between angular 1.5.0 and PhantomJs 1.x. I will attempt to implement a fix and submit a pr.

https://github.com/angular/angular.js/issues/13794
