### ISSUE TITLE
After remove item in array nya-bootstrap-select don't remove from option

### ISSUE THREAD

**Issue by rshmiraf** [lordfriend/nya-bootstrap-select#123]
Hi,
I use function splice() in my array. Angular see changes but select dont remove class selected. I've tried to add deep-watch="true" but nothing happend.

I want to "refresh" my select after do changes in array :)
https://scr.hu/K3LzyO <-- preview

Thanks

**Comment by lordfriend** [comment]
Can you provide a plunker example?

**Comment by rshmiraf** [comment]
@lordfriend  - http://plnkr.co/edit/YICatcPYBEDlfz0IsYn0?p=preview :)

**Comment by lordfriend** [comment]
This is very unusual case, there are dom manipulation in controllers, use of $compile service everywhere, I can't figure out what's going wrong, but I can only answer nya-bs-select directive's ngModelController.$render method isn't called after $scope.offer.skills model changed.
This is wired..if framework doesn't call my $render method, I have nothing can do.

**Comment by lordfriend** [comment]
well, I think I've found the problem,
I just add a watcher to $scope.offer.skills to see if it can detect the array's change.
when I add something from select, watcher can detect the change, but when I remove some element using X button from container, the watcher fails to detect this change, nothing happend.
So the key must be the offer.skills, It is an very wired data structure, skill is an property add to an Array, I think this may be a problem fro angular's watcher. You use offer.skill in template, But angular may not work properly with this syntax when offer is not an plain object

**Comment by rshmiraf** [comment]
But using X button from container remove my item in array. Problem is in nya-bs-option, becouse he dont remove class .selected. Do you have any function who render option one more time? 

When i add $scope.offer.skills = ["Spring","Hibernate"] it render well checked option, so i have no idea what im doing wrong using splice.

Maybe i can have in one variable my all option and in a second one have only selected?

**Comment by rshmiraf** [comment]
Problem is in splice... this dont work well.

Maybe doing a loop like:

for(var x, x<array.length; x++){
$scope.offer.skills = [ ADD OLD WITHOUT ONE ]
}

Will change something... I will try tomorrow

**Comment by rshmiraf** [comment]
i resolved this problem :) I can do splice only on my array. I need to add second one array and add them  everything without one. Later after each changes do only: $scope.offer.skills = $scope.offer.skillsHelper;
