### ISSUE TITLE
two way binding $scope.value

### ISSUE THREAD

**Issue by dontripi** [lordfriend/nya-bootstrap-select#124]
Hello i want to know how can bind in two ways the selected value in select because if i have the ng-model setted with $scope.value if i want to read $scope.value from controller directly i can't, the way i can do that is pass as parameter the value to a function in the controller so i can read that value, please if you can do some example reading the ng-model in the select from a controller, i will be thankful.

**Comment by lordfriend** [comment]
I don't learn what your need is. ng-model itself is a two way binding.

**Comment by dontripi** [comment]
but when i set the ng-nodel variable for example is called $scope.value = {}, then i choose some option in the select, but when i call alert(JSON.stringify($scope.value)); then i get {} is empty, but if send in some function in the view <button ngclick=somefunction(value)>click</button> then it works perfect.

**Comment by lordfriend** [comment]
scope change is managed by angular watchers, alert() will pause this mechanism. the best way to watch a scope model change is using a watcher, `$scope.$watch()`
It is recommended reading angular official guide to learn more about scope
https://docs.angularjs.org/guide/scope

**Comment by lordfriend** [comment]
Close due to no further question
