### ISSUE TITLE
Live search on server

### ISSUE THREAD

**Issue by profhase** [lordfriend/nya-bootstrap-select#125]
I would like to perform the live search on server data. Is there some builtin feature for that?

I tried this code (there is a `$watch` on `searchString` which requests `foundUsers` from server, but i cannot type into my input field

```
<div class="col-lg-6">
    <ol class="nya-bs-select
          ng-model="selectedUsers"
          title="Select Users"
          data-size="8"
          multiple>
          <div>
             <input class="form-control" ng-model="searchString">
           </div>
           <li nya-bs-option="user in foundUsers">
               <a>{{user}}</a>
            </li>
    </ol>
 </div>
```

**Comment by lordfriend** [comment]
Sorry, live search from remote source is supported, you can use [ng-tags-input](https://github.com/mbenford/ngTagsInput) for this feature

**Comment by profhase** [comment]
Thanks a lot, I will close the Issue.
