### ISSUE TITLE
Empty text for as title

### ISSUE THREAD

**Issue by Siferra** [lordfriend/nya-bootstrap-select#128]
Hello,

When we use an empty string in title option in `<ol>` or `<li>` tags, text is ignored and default value is set.
Is it possible to change this behaviour by changing `getDefaultNoneSelectionContent` function in nya-bs-select.js ?

Thanks
Seb

**Comment by lordfriend** [comment]
use `title-tpl="<span></span>"` should work, because empty string in javascript will be evaluated to false.

**Comment by Siferra** [comment]
Thanks for the reply, it works fine.
Just if you can add an entry in doc it would be helpful.
