### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by matt328** [lordfriend/nya-bootstrap-select#132]
Can you publish 2.1.6 to the npmjs.org registry?  Its not a huge deal, but it would allow those of us loading this via npm to avoid having a git url in package.json.

**Comment by lordfriend** [comment]
npm package of this project is already published by another guy, I will consider publishing a npm package with my user scope.

**Comment by lordfriend** [comment]
I publish this package into npm under my name scope. using `npm install @lordfriend/nya-bootstrap-select' to install this package.
