### ISSUE TITLE
Dynamic Enabling/Disabling

### ISSUE THREAD

**Issue by matt328** [lordfriend/nya-bootstrap-select#133]
Is there an example of this anywhere?  I'm using the `disabled` attribute on the `<ol>` element, and binding it to an attribute in my controller that toggles between `true` and `false`.  I am echoing {{controller.disabled}} on my page and can watch that value change, but the dropdown stays enabled.  What is the attribute, disable, disabled, nya-disable, nya-disabled, ng-disable?  The documentation doesn't mention it anywhere.

Edit: I reviewed the code and determined the proper attribute is 'disabled'.  However, even through I have `disabled="{{controller.isDisabled}}"`, the watch function is only ever called once when the value is initially set, and never again even though where I have `<pre>{{controller.isDisabled}}</pre>` is being changed from true to false and vice-versa.

**Comment by matt328** [comment]
I am using Angular 1.5.6 (if that makes any difference), and switching the disabled attribute from using `$scope.watch()` to `$attrs.$observe` (https://docs.angularjs.org/api/ng/type/$compile.directive.Attributes) seems to have fixed it for me:

https://github.com/matt328/nya-bootstrap-select/commit/0902bd6ee920e29bee039a60ce56d48d85d80d37#diff-cb89a6b6dd42ce4891a0580a8cce1f7c

I'm not sure if this is an issue with something that changed in Angular 1.5.6 or what, but I can submit a pull request if you want.

**Comment by lordfriend** [comment]
There are examples here:

http://nya.io/nya-bootstrap-select/#!/examples/form-control-feature
And besides, the API doc is laid here:
http://nya.io/nya-bootstrap-select/#!/api/nya-bs-select

`disabled` attribute is a two-way binding property which means you need use the property name on your controller scope directly instead of warpping with double brackets

**Comment by matt328** [comment]
This documentation is incredibly helpful.  I had not found it until just now, thanks!
