### ISSUE TITLE
Change selected item on focus with keyboard typing

### ISSUE THREAD

**Issue by capesean** [lordfriend/nya-bootstrap-select#141]
Is it possible to select the first option that matches what you are typing when the control has focus? Much like you could do with a plan HTML `select` control, so if you typed "TW" in this plnkr, it would select the option "TWO"...
http://embed.plnkr.co/zm0sQUMcYacNb4jNdpMM/

Is that currently possible?

**Comment by lordfriend** [comment]
Sorry, the feature is not implemented.
Maybe the `live-search="true"` would help

**Comment by capesean** [comment]
Thanks, that seems to work. Enter => opens the live search. Type = filter until the correct one is selected. Enter => select & close.

:+1:
