### ISSUE TITLE
data-container support

### ISSUE THREAD

**Issue by ChiggerChug** [lordfriend/nya-bootstrap-select#145]
I saw on the main page that data-container had been struck out on the future development list. Why is that? I love this plugin, I'm using it everywhere in my application but this is a needed feature for a panel I'm adding a drop-down list to (see example below)
![issue](https://cloud.githubusercontent.com/assets/6593130/19351894/67da1b9c-9155-11e6-84f0-4106f4876f66.png)
I need this drop-down to appear above the panel, is this not possible? 
_Is there a hacky way I could do this in the short term?_

**Comment by lordfriend** [comment]
Because the data-container support need measure the position, and handle corner case. which need a lot of work. 
The requirement for this feature usually occur when you're using this directive inside an container which has a `overflow: hidden` style.

**Comment by cloudstrifebro** [comment]
Does this mean that we can't do what you've suggested here, and that we can't simply add data-container="body"?

https://github.com/lordfriend/nya-bootstrap-select/issues/1

**Comment by lordfriend** [comment]
@cloudstrifebro #1 issue is for the 1.x version which is a simple wrapper of the jquery bootstrap-select. The current version is a rewrite not require jquery and bootstrap-select.
