### ISSUE TITLE
Combine static and dynamic options

### ISSUE THREAD

**Issue by nasrinmithila** [lordfriend/nya-bootstrap-select#146]
Combining static and dynamic options throws an error: 'Cannot read property 'option' of undefined'.
```
<ol
    ng-model="search"
    class="nya-bs-select"
    multiple
>
  <li 
         class="nya-bs-option" data-value="">
         <a>- Clear -</a>
  </li>
  <li nya-bs-option="option in options">
       <a>
             {{option.name}}
       </a>
  </li>
</ol>
```

**Comment by lordfriend** [comment]
Combining static and dynamic options is not supported

**Comment by nasrinmithila** [comment]
Thanks for your reply.

**Comment by mrsus** [comment]
@nasrinmithila I tried ng-repeat and it worked.

    <ol
        ng-model="search"
        class="nya-bs-select"
        multiple
    >
       <li 
             class="nya-bs-option" data-value="">
                <a>- Clear -</a>
        </li>
        <li class="nya-bs-option" ng-repeat="option in options" data-value="option.name">
                <a>
                        {{option.name}}
                </a>
         </li>
    </ol>
