### ISSUE TITLE
Add "main": "dist/js/nya-bs-select.js" to package.json

### ISSUE THREAD

**Issue by martinmicunda** [lordfriend/nya-bootstrap-select#152]
Is it possible you could add dist file path to `package.json`. This is handy when someone use `jspm`, `webpack` or some other tools? Thanks

```
"main": "dist/js/nya-bs-select.js"
```

**Comment by lordfriend** [comment]
Sorry, I've added this in `bower.json` but forgot to add in `package.json`. I'll fix this asap.

**Comment by martinmicunda** [comment]
@lordfriend Could you also publish a new version to npm. The current version is still `2.1.9`. Thanks

**Comment by lordfriend** [comment]
Published!
