### ISSUE TITLE
IE Scrollbar bug

### ISSUE THREAD

**Issue by MrWook** [lordfriend/nya-bootstrap-select#164]
Hello,

i encounter the same problem as in #78. The IE can't handle an expression in the attribute "disabled" like it should be. So if you use the disabled property from nya-bs-select the scrollbar gets bugy.
You can see this problem in this [Plunker](https://plnkr.co/edit/vuaLhtJADChcpJFe0tS0?p=preview)
Besides that i tried to use `ng-disabled` instead but with that the dropdown don't get disabled.
I encounter this problem in IE 11 to be specific in version 11.0.9600.18638
Maybe i'm missing something can you provide me with some help please?

 

Kind regards
MrWook

**Comment by lordfriend** [comment]
Sorry, I don't have the environment to debug this issue. Maybe you can help to solve this issue and make PR.

**Comment by lordfriend** [comment]
ngDisabled support is added, thank you for contributing
