### ISSUE TITLE
Dropup from bootstrap-select 

### ISSUE THREAD

**Issue by ghiscoding** [lordfriend/nya-bootstrap-select#172]
Hello and thanks for the great library, I use it in all my projects now.

I see that maybe a feature from `bootstrap-select` is missing which I find convenient is the [dropup](https://silviomoreto.github.io/bootstrap-select/examples/#dropup-menu). I work a little on it and got it working however in a manual way (which means that if you want it to go up, you tell it `dropup`, else it will go down)
Do you think it would be good to add to your current code? I only added this piece of CSS

```css
.nya-bs-select.btn-group .dropdown-menu.open.dropup {
  top: auto;
  bottom: 100%;
  margin-bottom: 2px;
}
```
and then in the Directive usage, I simply added the `dropup` class on the ones that I wanted it to go up, like this
```html
<ol class="nya-bs-select dropup" ...>
```
To my surprise, the carret (arrow) is also working correctly, I didn't have to add CSS for it.

The best would be to have the `dropup` work automatically (like in `bootstrap-select`), but for that there's code change to apply in JS with calculation of the offset and position of the dropdown in the viewport and I didn't spend time on that since in my case they were always in the bottom of my screen and I always wanted the `dropup`.

With this simple CSS change and adding the `dropup` class, the result is the following (it's displayed up):

![dropup](https://cloud.githubusercontent.com/assets/643976/26122823/d1884894-3a46-11e7-9bd2-8170887903fc.png)

A feature request would be to make it automatically detect if it needs to go up or down, but I'm also happy with manually detecting it like I currently have implemented.

**Comment by lordfriend** [comment]
Well, Yes, this is a missing feature from the beginning of the 2.0 development. Because dropup need some script to check the absolute position of the dropdown button related with viewport. In the time of development, I don't know how to implement that. Although now I think I know how to achieve that check. but the time is not for this.

I think you have read the REAMDE notice about this project status. This project is in a **MAINTANENCE STATUS** and will not add any feature.

So It won't be added.

**Comment by ghiscoding** [comment]
Ok you can close it if you want then. What I provided works for a manual trigger, if people are interested in it they could use the code I provided. 

I'm just curious though, I provided some CSS. Could that be added to the CSS or you are really closed to any modifications since you are in maintenance?

Thanks

**Comment by lordfriend** [comment]
Adding  a feature is not only adding some code to the source and publish a version. It also need a lot of consideration to avoid break the old feature, need write new test, document. It took some hours.
