### ISSUE TITLE
Dynamic attribute "multiple"

### ISSUE THREAD

**Issue by marcomelilli** [lordfriend/nya-bootstrap-select#176]
The attribute "multiple" works always when it's present, event if I set `multiple="false"`
I think it's useful to be able to change that boolean in many scenarios.

In the function "_getDefaultNoneSelectionContent_" and "_nyaBsSelectLink_" I suggest this:

`...    
isMultiple = typeof tAttrs.multiple !== 'undefined' && tAttrs.multiple !== 'false',
...
`

**Comment by lordfriend** [comment]
Use `ngSwitch` or `ngIf` to wrap two different types of select. 

This project won't change dramatically anymore.
