### ISSUE TITLE
Ajax as a data source

### ISSUE THREAD

**Issue by piernik** [lordfriend/nya-bootstrap-select#19]
Can You make that data will be loader through ajax? ui-select has `refresh` and `refresh-delay` attrbs

**Comment by piernik** [comment]
Hi, when You think You'll manage to make new version?

**Comment by piernik** [comment]
any news??

**Comment by lordfriend** [comment]
I haven't found any way to make this.

**Comment by piernik** [comment]
Do You mean That You won't add it?? Take ui.bootstrap as a source. You have to add this option and Your select component will be the best...

**Comment by piernik** [comment]
Sorry for bother.
I need Your declaration, because it's very important form me.
Are You making ajax handling or not?
If not I have to look for other solution.

**Comment by lordfriend** [comment]
No, Ajax is not planned. Sorry for this.

**Comment by dorrotman** [comment]
I am using the component, and this feature is missing for me too. I may develop this internally in the future. Are you open to PRs on this? 
Thanks.

**Comment by lordfriend** [comment]
Add ajax data source may make this component too wired.
