### ISSUE TITLE
Title with text-muted class

### ISSUE THREAD

**Issue by piernik** [lordfriend/nya-bootstrap-select#22]
Can You use 
```
<span class="text-muted">{{title}}</span>
```
when You define title attr? Then it will look like placeholder in normal input.

**Comment by lordfriend** [comment]
Supported in v2.0.6
See document
http://nya.io/nya-bootstrap-select/#!/api/nya-bs-config-provider

**Comment by bartekringwelski** [comment]
I had this issue and changed the title color (which I'm using to mimic a placholder) by modifying the CSS of the bower component:

.nya-bs-select .dropdown-toggle .special-title {
  display: none;
  color: rgb(60%, 60%, 60%);
}
