### ISSUE TITLE
Dropdown only gets triggered on second click

### ISSUE THREAD

**Issue by zhenghao1** [lordfriend/nya-bootstrap-select#36]
Hi, 

I just wanted to throw this out there to see if anyone else is experiencing this.  When I load the page, the `<ol class="nya-bs-select">` element does not have the class `open`.  I set a breakpoint at:  

[Line 270 of nya-bs-select.js](https://github.com/lordfriend/nya-bootstrap-select/blob/master/src/nya-bs-select.js#L270)

When I click on the `dropdownToggle` or the `<button>`, the `$element` HTML which refers to the `<ol>` now contains the class `open`.  Naturally line 270 will negate that and cause the dropdown to not show up.  Hence a second click is required to show the dropdown.

I know this is weird, but I'm at my wits ends as to where could the `open` class be possibly added to the HTML when I click the dropdownToggle for the very first time after page load.  Anyone?

**Comment by zhenghao1** [comment]
Sorry, this is my problem.  AngularUI Bootstrap does not play nice with nya-bootstrap-select.  nya-bootstrap-select uses a class called `dropdown-toggle` which clashes with AngularUI Bootstrap directive dropdownToggle.

**Comment by lordfriend** [comment]
This directive is design to work with ui-bootstrap. the dropdown toggle of ui-bootstrap is an element/attribute directive not a class. It shouldn't conflict with this.

**Comment by zhenghao1** [comment]
Ok, maybe I wasn’t specific about the version of ui-bootstrap.  I’m using 0.8.0, the last one compatible with Bootstrap 2.3.2.  

This version of ui-bootstrap has a dropdownToggle directive of either an ATTRIBUTE or CLASS.  Hence the class conflicts with nya-bs-select.
