### ISSUE TITLE
Clear selected item after form submission

### ISSUE THREAD

**Issue by fproldan** [lordfriend/nya-bootstrap-select#39]
Hi! How i can clear the selected item after form submission?, te value of the ng-model turn empty but the widget still show the previous selected item.

Sorry for my english

Thanks

**Comment by cypherix93** [comment]
+1 

The ng-model value can be changed to null, but the dropdown stays the same. We need a way to deselect.

**Comment by jca258** [comment]
Hi, I have a PR to solve that. I make the component get unselected when the component is undefined.
https://github.com/lordfriend/nya-bootstrap-select/pull/42 you only have to get an option with the value set to "" or not defined to get the unselected status or if you want to get the unselected value from the controller, you can set the model to undefined.

Please make +1 in the PR.
