### ISSUE TITLE
component will not work when debug info is disabled

### ISSUE THREAD

**Issue by ricardocasares** [lordfriend/nya-bootstrap-select#43]
The methods `.scope()` and `.isolateScope()` of an `angular.element` will return undefined when debug info is disabled: `$compileProvider.debugInfoEnabled(false);` as stated [here](https://github.com/angular/angular.js/issues/9515) and  [here](https://docs.angularjs.org/api/ng/function/angular.element#methods).

So [this piece of code](https://github.com/lordfriend/nya-bootstrap-select/blob/master/src/nya-bs-select.js#L674) won't work while running your app on production mode:

```javascript
function getOptionValue(nyaBsOption) {
  var scopeOfOption;
  if(valueExpFn) {
    scopeOfOption = nyaBsOption.scope(); // won't work on prod
    return valueExpFn(scopeOfOption);
  } else {
    if(nyaBsSelectCtrl.valueIdentifier || nyaBsSelectCtrl.keyIdentifier) {
      scopeOfOption = nyaBsOption.scope(); // won't work on prod
      return scopeOfOption[nyaBsSelectCtrl.valueIdentifier] || scopeOfOption[nyaBsSelectCtrl.keyIdentifier];
    } else {
      return nyaBsOption.attr('value');
    }
  }
}
```

**Comment by ricardocasares** [comment]
+1

**Comment by yamil777** [comment]
+1

**Comment by jca258** [comment]
+1

**Comment by lordfriend** [comment]
It is hard to fix this.

**Comment by jibap** [comment]
Hi !

This issue seems to be resolved in 'src' files but not replicated in 'dist' compilation ... How to use a version with last commits ?

Thanks

**Comment by lordfriend** [comment]
I'll draft a release in this weekend.
Although This bug was fixed, but there are several other changes need to be tested and other bugs need to be resolved.
