### ISSUE TITLE
Missing selected item

### ISSUE THREAD

**Issue by levipadre** [lordfriend/nya-bootstrap-select#45]
Hi,

Thank you for your great directive.
I have a little problem, when I use static list. The selected item didn't highlighted and showed the text, not even your example (http://nya.io/nya-bootstrap-select/#!/main/getting-started).
```
<ol class="nya-bs-select" ng-model="model" title="Sort by...">
   <li class="nya-bs-option"><a>Default state</a></li>
   <li class="nya-bs-option"><a>Name (A-Z)</a></li>
   <li class="nya-bs-option"><a>Name (Z-A)</a>
</ol>
```

Thanks,

**Comment by jca258** [comment]
Hi,

Try to use the value="" parameter in the li to have a value to assign to the model.

**Comment by lordfriend** [comment]
Example for static list lies here:
http://nya.io/nya-bootstrap-select/#!/examples/basic-usage

**Comment by levipadre** [comment]
Still not working with value, and I double-checked the example, and always shows the same: "Nothing selected"

**Comment by lordfriend** [comment]
I see, this is a new bug

**Comment by levipadre** [comment]
Thanks!
