### ISSUE TITLE
Multiple Attribute Throws error

### ISSUE THREAD

**Issue by natevecc** [lordfriend/nya-bootstrap-select#49]
Hi thanks for this great project. I'm using version 2.0.10 and ran into an edge case that's throwing an error. The problem is [here](https://github.com/lordfriend/nya-bootstrap-select/blob/master/src/nya-bs-select.js#L734) and caused by `modelValue` being null.

`modelValue` is null because I wanted to reset the select to nothing as a cancel button has been clicked. Maybe checking for it's existence on the offending line or defaulting it to an empty array might fix the problem.

**Comment by lordfriend** [comment]
If you use multiple attribute, you should set `modelValue` to an empty array `[]`

**Comment by rshmiraf** [comment]
Its work @lordfriend :) thanks!

**Comment by ghiscoding** [comment]
I also had this issue and it's cause by the `if` on this line
_(with current code it's on line 890)_

```javascript
// line 890
if(isMultiple && viewValue.length === 0) {
    dropdownToggle.addClass('show-special-title');
    filterOption.empty();
}
```

The fix is to make sure the `if` doesn't throw an error
```javascript
// line 890
if(isMultiple && (!viewValue || viewValue.length === 0)) {
...
```

The error thrown, prior to the quick fix, was the following (see below). This went away after the quick fix. 
```shell
angular.js:13550 TypeError: Cannot read property 'length' of null
    at updateButtonContent (http://localhost/sqt/Scripts/nya-bs-select.js:1300:37)
    at NgModelController.ngCtrl.$render (http://localhost/sqt/Scripts/nya-bs-select.js:876:11)
    at ngModelWatch (http://localhost/sqt/Scripts/angular.js:26948:14)
    at Scope.$digest (http://localhost/sqt/Scripts/angular.js:17064:34)
    at Scope.$apply (http://localhost/sqt/Scripts/angular.js:17337:24)
    at done (http://localhost/sqt/Scripts/angular.js:11572:47)
    at completeRequest (http://localhost/sqt/Scripts/angular.js:11778:7)
    at XMLHttpRequest.requestLoaded (http://localhost/sqt/Scripts/angular.js:11711:9) undefined
```

**Comment by lordfriend** [comment]
viewValue ( aka, modelValue) be null is unexpected behavior. You should not set it to null. It can be undefined or `[]`

**Comment by ghiscoding** [comment]
@lordfriend the problem is we don't always have control on what is sent from the backend WebAPI and we have to deal with it on the frontend. Why not put in place the 1 line fix I sent? It's easy and avoid throwing errors. In a perfect world, code should never throw errors and yours does, so why not fix it?

**Comment by lordfriend** [comment]
I don't remember why multiple selection modelValue can't be null.

Just review the code, many lines need change not only that one line if you want to allow null as modelValue

**Comment by ghiscoding** [comment]
Thanks for the reply @lordfriend in my case the quick fix was mostly to remove the possibility of getting an error thrown in the console and yes I have to say that I only changed the line that throw an error on my side. We want to avoid having code throwing error. If we look at the `viewValue` variable, then the only other place that it could throw an error is on line 1326. 

So in the end, that would be 2 lines to change to avoid error thrown

```javascript
// line 890
// change this
if(isMultiple && viewValue.length === 0) {

// to this
if(isMultiple && (!viewValue || viewValue.length === 0)) {
```

and next line
```javascript
// line 1326
// change this
if((typeof count !== 'undefined') && viewValue.length > count) {
..
// to this
if((typeof count !== 'undefined') && (viewValue && viewValue.length > count)) {
```

This does not change the behavior of the code in any sense, except that it won't throw false error when `viewValue` is `null` and the UI won't be broken anymore, apart from the select being empty.

Thanks for your plugin, I now use it in all my projects :)

**Comment by lordfriend** [comment]
I'll review this
