### ISSUE TITLE
feat: ability to use angular binding in title attribute

### ISSUE THREAD

**Issue by jpmckearin** [lordfriend/nya-bootstrap-select#53]
I need to be able to run my "title" through a filter before showing it on the screen. Because the value of the title attribute is simply copied in the compile function of the nyaBsSelect directive, it seems we can't accomplish this without moving the logic into the link function and using the $compile service to do it there. Any thoughts?

Example:

```html
<ol class="nya-bs-select" ng-model="dynModel" title="{{ 'SOME TITLE' | someFilter }}">
    <li nya-bs-option="option in options">
        <a>
            {{option.name}}
        </a>
    </li>
</ol>
```

**Comment by lordfriend** [comment]
This feature is requested in #22 and has already been supported but currently undocumented.

Instead of using `title` attribute, using `title-tpl` attribute will allow you binding data or further more, add html tags as your *nothing select* button presentation.

**Comment by jpmckearin** [comment]
I attempted that but had no luck. Will create a codepen as soon as I get a chance.

**Comment by lordfriend** [comment]
It seems that jquery fails to recogonize what the string {{ 'Custom Title' | upper }} represents for. 
To solve this, wrap your string with an inline tag like `<span>`

`title-tpl="<span>{{ 'Custom Title' | upper }}</span>"`

This will work

**Comment by jpmckearin** [comment]
You are correct. That works great. Thanks!

**Comment by spanmo** [comment]
seems to be broken in current version. also, the official api doc seems to state specifically that bindings are not working.
Any thoughts?
