### ISSUE TITLE
Unable to apply bootstrap button styles such as btn-sm btn-xs, etc

### ISSUE THREAD

**Issue by alexmnyc** [lordfriend/nya-bootstrap-select#55]
Unable to apply bootstrap button styles such as btn-sm btn-xs, etc

This line needs to be changed to allow for all buttons styles not just danger, warning, etc.

if(/btn-(?:primary|info|success|warning|danger|inverse)/.test(className)) {

btn-*

**Comment by lordfriend** [comment]
Close this issue as it has been resolved
