### ISSUE TITLE
live-search keeps selected the first match item when "NO SEARCH RESULT"

### ISSUE THREAD

**Issue by jibap** [lordfriend/nya-bootstrap-select#60]
Hi !

I'm in v2.0.10
In live-search, when there is no result, the option "NO SEARCH RESULT" is shown, but the first item is selected if we press "enter" key. 

I fixed it (looking https://github.com/lordfriend/nya-bootstrap-select/pull/56 @erlis commit) removing <code>&& childElement.hasClass('selected')</code> in <b>findFocus</b> function, but it corrupt the opening behaviour (focus selected)

An other issue linked: if you select multiple options but not first,if you re-open the dropdown and navigate with keyboard, on bottom key, it loop on selected options. (the code edit above also fix this issue)

It is my first time i look your code, but i think it exists a better way to fix

**Comment by lordfriend** [comment]
Thanks for feedback, I have found the issue, and resolved it with adding an condition which will check whether an element has `not-match` class in **findActive** function.
This issue will be resolved in next release

**Comment by jibap** [comment]
I tested it on my project, i confirm it fix the issue. I close this issue but don't forget the other part ;-)

**Comment by jibap** [comment]
Reopen, hopping for update

**Comment by tangorri** [comment]
+1
