### ISSUE TITLE
required or ng-required attribute support?

### ISSUE THREAD

**Issue by minutephp** [lordfriend/nya-bootstrap-select#62]
Hi,

How to add the `required="true"` or `ng-required` support so that when the user is trying to submit the form without selecting anything a `HTML5` popup can prompt her to select something first (like a normal select box)?

Is there a way to do this?

Thanks!
San

**Comment by lordfriend** [comment]
Currently, `required` and `ngRequired` should be supported but the document need to be improved.

See http://nya.io/nya-bootstrap-select/#!/examples/form-control-feature for more details

**Comment by minutephp** [comment]
Hi, thanks for the reply.. Is it some dev branch that has added support for it? 

Right now the stable branch (that i installed with bower) doesn't seem to support `required` or `ng-required`.

**Comment by lordfriend** [comment]
dev branch only updated document, I should supported in stable branch

**Comment by minutephp** [comment]
gotcha.. I see it is working. But is there a way to create browser prompts when the user submits the form, similar to text inputs?

![image](https://cloud.githubusercontent.com/assets/10337558/8023054/8b5b3c82-0d16-11e5-9eb9-3446ff07f877.png)

**Comment by lordfriend** [comment]
Maybe, it cannot be done automatically, because neither <nya-bs-select> nor <ol> is a form component, so I have to implement an promote by yourself.
As the document example shows, by checking the $invalid property to display a tip, using other tip components

**Comment by minutephp** [comment]
I agree. thank you again for the replies and explanation.
