### ISSUE TITLE
ng-model $parent scope problem

### ISSUE THREAD

**Issue by brndusic** [lordfriend/nya-bootstrap-select#63]
There is a problem for me, I made a directive which uses this selectpicker. Problem is that I need to set ng-model like $parent.model to be able to access model value from my directive controller. I'm also using there other directives but with them I have no problems.

``` html
<ol class="nya-bs-select" ng-model="$parent.hour">
     <li nya-bs-option="h in hours" value="h.value">
                <a>
              {{h.formatted}}
                </a>
      </li>
</ol>
<span>Horu: {{hour}}</span>
```

**Comment by lordfriend** [comment]
nyaBsSelect is a directive which **does not create an isolated or inherit scope**. If you want access the directive containing controller, you should access it directly. $parent is not needed. I don't know what the other directives are, but I think those directive is an anti-pattern design for using ng-model

**Comment by brndusic** [comment]
Closing as it is irrelevant for me after a lot of time. Thanks @lordfriend
