### ISSUE TITLE
view value is not using the latest selected option when using $validators

### ISSUE THREAD

**Issue by odiwodi** [lordfriend/nya-bootstrap-select#65]
Hello! I have this directive that implements a validation using $validator. The validator successfully checks the model value upon changing, though the view value is delayed.

For an example, I have a dropdown with 3 options namely A, B, and C.
It should be valid when B or C is selected.
On initialization, the view is blank as its ngModel.
Issue comes when I select B, the view value is still "None Selected" but model value is B.
Then when I select A, the view value becomes B and the model value becomes A.
It correctly attaches the invalid state of the control, but the view value is delayed..

BTW, this is a great directive. Thanks! ;)

**Comment by odiwodi** [comment]
I used $parser and $formatters instead of $validators, and luckily has fixed the issue.
I hope this can save someone's arse from hours of research in the future. :)

**Comment by lordfriend** [comment]
I think this is the fault of angular document
https://github.com/angular/angular.js/issues/10035
