### ISSUE TITLE
'item selected' instead of 'items selected' when multiple are selected

### ISSUE THREAD

**Issue by KirylKazlovich** [lordfriend/nya-bootstrap-select#66]
The text in picklist says 'item selected' instead of 'items selected' when multiple are selected
<img width="457" alt="screen shot 2015-07-09 at 09 01 33" src="https://cloud.githubusercontent.com/assets/9461079/8588968/6f6f42c2-2619-11e5-81e6-ddbefb14c857.png">

**Comment by devakone** [comment]
Noticed the same thing as well.
