### ISSUE TITLE
"as-for-in" syntax in nya-bs-option

### ISSUE THREAD

**Issue by jonkri** [lordfriend/nya-bootstrap-select#74]
Hi, again!

With ng-options, it's possible to write like this:

    ng-options="item.uuid as item.name for item in items"

This has the benefit of allowing the model value to a different sub-property from the captions enumerated in the select box.

Would it be possible to allow for the same capability in <code>nya-bs-option</code>?

Thanks!

**Comment by lordfriend** [comment]
`nyaBsOption` is base on `ngRepeat` and add support for grouping options. to keep the syntax simple. I use a individual attribute `value` (next version will be data-value, but will be compatible with value), which defines the expression for model value.
See the example for `value` attribute here:
http://nya.io/nya-bootstrap-select/#!/examples/groups-and-more
