### ISSUE TITLE
IE Scrollbar "Disabled"

### ISSUE THREAD

**Issue by jpmckearin** [lordfriend/nya-bootstrap-select#78]
Any clue what could cause this? Notice the scrollbar seems to almost be disabled. There are approx 50 items in that dropdown, and for reference the scroll works just fine in Chrome/FF. 

![ie scrollbar issue](https://cloud.githubusercontent.com/assets/6679168/9100527/77037740-3ba1-11e5-92fd-9de9ad496322.PNG)

**Comment by lordfriend** [comment]
May be caused by `overflow-y: auto;'
https://github.com/lordfriend/nya-bootstrap-select/blob/master/src/nya-bs-select.js#L929-L932

Could you tell me Which IE version has this bug?

**Comment by jpmckearin** [comment]
I found the issue. Guess I just needed to sleep on it. Someone used disabled instead of ng-disabled, which caused the IE scrollbar to disabled because IE processes the disabled tag a little differently. Thanks for your time.
