### ISSUE TITLE
When no options present, component not rendered

### ISSUE THREAD

**Issue by garyns** [lordfriend/nya-bootstrap-select#8]
When there are no options present in a nya-selectpicker, the component does not get markup. 

A workaround could be to include an empty option if there is no data in the model, like:
    &lt;option value="" ng-hide="jobs.length != 0"&gt;&lt;/option&gt;

**Comment by radiart** [comment]
in nya-bs-select.js change

      if(!modelValue) {
        return;
      }
to

      if(!modelValue) {
        filterOption.empty();
    filterOption.append(document.createTextNode($attrs.title));         
        return;
      }
