### ISSUE TITLE
How do you reset to a empty model ?

### ISSUE THREAD

**Issue by GBora** [lordfriend/nya-bootstrap-select#80]
How do I give the user a option to reset to a empty model even after he's selected an option.

I've tried to createing a static option with a value of null/undefined/'' but it doesn't work

**Comment by lordfriend** [comment]
For multiple select mode, This pr give an possibility to unselect all option
For single select mode, There shouldn't be an mechanism to unselect option. If you need to unselect, you can reset model by a normal button

**Comment by GBora** [comment]
@lordfriend  :)) tell that to my users they expect to be able to ctrl-z every single thing they do even in single select mode.

Thanks for asnwering so quickly, I may ask one more question: I need to call a function on select with a value from the nya-bs-option which was selected, how can I do this besides ng-change ?

**Comment by lordfriend** [comment]
Sorry, No callback is supported, This directive is aimed to working with ng-model

**Comment by GBora** [comment]
Ok, thanks.

**Comment by capesean** [comment]
You could make this small change for clearing the single-mode select value from the model, when the user clicks a selected option a second time:

Change:

```
              dropdownMenu.children().removeClass('selected');
              if (modelValue == viewValue)
              viewValue = value;
              nyaBsOption.addClass('selected');
```

to:

```
              dropdownMenu.children().removeClass('selected');
              if (modelValue !== value) {
                  viewValue = value;
                  nyaBsOption.addClass('selected');
              }
```
