### ISSUE TITLE
Options issue on bootrstrap-select.js

### ISSUE THREAD

**Issue by kkerezsi** [lordfriend/nya-bootstrap-select#81]
Hello, 

I've encountered a strange issue with liveSearch when trying to search for items that are not in the list . 
There is a exception thrown with the message : "Uncaught TypeError: Cannot read property 'options' of undefined" . 
My bootstrap-select.js version is v1.7.3 . I think this might the issue but have no clue how to fix this without replacing the bootstrap-select file.

Kind regards,
Alex

**Comment by lordfriend** [comment]
The old version of this directive cannot catch up the update of the Bootstrap-select, If you cannot switch to use the new version of this directive. downgrade Bootstrap-select to 1.4.x

However, If you are using nya-bootstrap-select above 2.0.0, you don't need Bootstrap-select. It doesn't depend on that.

**Comment by kkerezsi** [comment]
Thank you for your response . Wish you an excellent day !
