### ISSUE TITLE
Disabled attributes not working with last version of angular-ui bootstrap dropdown directive

### ISSUE THREAD

**Issue by jibap** [lordfriend/nya-bootstrap-select#82]
In UI bootstrap v0.13.3, disabling nya-bs-select is not working.

I fixed it in <code>nyaBsSelectLink</code> function, replacing add/remove <b>class</b> by add/remove <b>attr</b> "disabled".

@lordfriend : are you alive ?

**Comment by GBora** [comment]
+1 Having the same issue.

**Comment by lordfriend** [comment]
yes, i've alive, but currently I cannot make some time to publish new version.

**Comment by jibap** [comment]
Ok, good new !!

CurentIy i use your version from your demo website, with this issue fixed and this other : https://github.com/lordfriend/nya-bootstrap-select/issues/

Best regards

**Comment by jonkri** [comment]
Hey guys!

On a related note, I was thinking if it would be possible to, in addition to being able to disable the list element, also be able to disable individual list items. Do you think that makes sense?

Thanks!

**Comment by jonkri** [comment]
@jibap: Thanks for the comment about how to fix It seems like you referenced the wrong issue above. You are referencing #82, which is this issue. May I ask which issue you wanted to reference?

**Comment by jonkri** [comment]
By the way, regarding my question in https://github.com/lordfriend/nya-bootstrap-select/issues/82#issuecomment-162878068, I noticed that list elements can be disabled [here](http://nya.io/nya-bootstrap-select/#!/examples/disable-an-option).

**Comment by jonkri** [comment]
Another thing that I have noticed in regards to this, which might be interesting to take into consideration, is that when a disabled select becomes enabled, it doesn't get the right color in IE9. The color changes from light gray to gray (so it looks a little less disabled, but it still looks disabled).

**Comment by jibap** [comment]
@jonkri : you're right, it was https://github.com/lordfriend/nya-bootstrap-select/issues/60

**Comment by jonkri** [comment]
Thanks!

**Comment by jibap** [comment]
FIXED in v2.3.1 !
