### ISSUE TITLE
CSS class on the button when nothing selected

### ISSUE THREAD

**Issue by capesean** [lordfriend/nya-bootstrap-select#83]
It would be great if you could add & remove a "none-selected" class (or similar) to the button when something is selected or not. That way, you could style the button text to mimic the behaviour of a placeholder, i.e. light-grey when nothing is selected; dark grey / blank when something is selected.

**Comment by lordfriend** [comment]
None-selected can be configured by `nyaBsConfigProvider` service globally or using `title-template`
http://nya.io/nya-bootstrap-select/#!/api/nya-bs-config-provider

**Comment by capesean** [comment]
I don't mean changing the **text** of the None-selected button, I mean adding/removing a class so the text can be styled if nothing is selected.

**Comment by lordfriend** [comment]
But you can use you own template instead of the default text. this means it has a class which you can add some style.

**Comment by capesean** [comment]
Sorry, I have no idea how to do that / use that. Here's a plunkr: http://plnkr.co/edit/XPqygldrgcWVZHpw7AsR?p=preview - would you mind showing me how to use the `nyaBsConfigProvider`?

**Comment by lordfriend** [comment]
http://plnkr.co/edit/NKli9PPtuy7rRkvp6nkz?p=preview

**Comment by capesean** [comment]
Thank you!
