### ISSUE TITLE
searchBox.off() is not a function

### ISSUE THREAD

**Issue by jekelhart** [lordfriend/nya-bootstrap-select#86]
Hey,

if I use nya-bs-select in a ng-repeat loop and save the parent (resource $save). The error "searchBox.off() is not a function" appears for every dropdown in the loop. After some delay everything is loaded correctly and works as expected.

If I debug the line 1358 in the source code searchBox is an empty array.
I'm not sure if there is something I have to consider when using nya-bs-select in a ng-repeat loop?

**Comment by lordfriend** [comment]
Would you please give a jsfiddle example?
searchBox is initialized at link phase, searchBox.off() is executed in event handle on `$destroy` event is fire on current scope

**Comment by frlinw** [comment]
Same here

![image](https://cloud.githubusercontent.com/assets/11896237/9662016/c77c0f48-525d-11e5-9213-67f56e38dfac.png)

with only one select 

```
<ul class="nya-bs-select" style="width:60px" ng-model="vm.pageSize" ng-change="vm.changePage()">'
      <li class="nya-bs-option" data-value="10"><a>10</a></li>
      <li class="nya-bs-option" data-value="20"><a>20</a></li>
      <li class="nya-bs-option" data-value="40"><a>40</a></li>
      <li class="nya-bs-option" data-value="80"><a>80</a></li>
 </ul>
```

**Comment by frlinw** [comment]
You are trying to do searchBox.off() at line 1358, but searchBox exist only if data-live-search="true" that's why there is an error with a normal select

**Comment by areim3r** [comment]
also getting this same error: 

![nya-err](https://cloud.githubusercontent.com/assets/8661521/9694263/d7c9bad6-530b-11e5-9c5e-98350dacda5f.png)

![screen shot 2015-09-04 at 1 57 07 pm](https://cloud.githubusercontent.com/assets/8661521/9694374/eb454548-530c-11e5-8a8a-885fa2f35c5b.png)

wrapping it in an if gets rid of the error for now

```javascript
if(searchBox.off){searchBox.off();}
```

**Comment by rda-dev** [comment]
Same issue

http://embed.plnkr.co/zm0sQUMcYacNb4jNdpMM/

**Comment by frlinw** [comment]
PR has been merged to correct this issue.

But the project seems to be idle, he lives thanks to PR. I think I have to lose one or two days to dev my own directive.

**Comment by lordfriend** [comment]
Sorry for response late, I've draft a new release with PR #93

**Comment by spanmo** [comment]
the build was not created in the current release thus the fix is not active when fetching it with bower. could you update the release?
thx!
