### ISSUE TITLE
Question: change the nothing selected text?

### ISSUE THREAD

**Issue by ganySA** [lordfriend/nya-bootstrap-select#97]
Is there any means to change the nothing selected text?

**Comment by josbol** [comment]
Hi ganySA, 

yes you can. You have to use the nyaBsConfigProvider for that:

For example (Brazilian Portuguese):

```javascript
angular.module('YourApp').config(function (nyaBsConfigProvider) {
 nyaBsConfigProvider.setLocalizedText('pt-br', {
        defaultNoneSelection: 'Selecione...',
        noSearchResult: 'Pesquisa sem resultados',
        numberItemSelected: '%d itens selecionado(s)'
    });
    nyaBsConfigProvider.useLocale('pt-br');

**Comment by ganySA** [comment]
Hi
Sorry i was hoping for something per drop down e.g 

Please select a fruit
Please select your title

etc.

**Comment by lordfriend** [comment]
use `title` or `title-tpl` attribute on `nya-bs-select` directive

**Comment by ganySA** [comment]
great thanks!

**Comment by sebius8780** [comment]
This should go into the .md or wiki section !!

**Comment by doppio** [comment]
FYI, `title` also changes the tooltip when mousing over the select box (even while something is selected). So @ganySA would see "Please select a fruit" when mousing over the select, even if "Apple" was already selected.
