### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by mattlewis92** [lordfriend/nya-bootstrap-select#98]
Hi there,

The latest version of [this module on npm](https://www.npmjs.com/package/nya-bootstrap-select) is `2.0.11`, please could you publish `2.1.2` to it when you have a sec please.

Thanks! :smile:

**Comment by lordfriend** [comment]
The npm package of this project is published by other guy, not me please contact the publisher on npm

**Comment by mattlewis92** [comment]
Ah that's annoying, thanks anyway!
