### ISSUE TITLE
title-tpl not working with the angular translate filter

### ISSUE THREAD

**Issue by GBora** [lordfriend/nya-bootstrap-select#99]
Hello I'm using the angular translate package and I'm trying to set the title for my select like so:
 `title-tpl="<span>{{ 'general.SelectPartner' | translate }}</span>"`

And it doesn't work the span gets generated but the key is not translated, please reply I convinced my colleagues to use your plugin all over our site due to it's wealth of features and lack of bugs, but internationalisation is a key feature for us and reading some of the comments here on github I'd thought it was possible with title-tpl.

**Comment by lordfriend** [comment]
But I tried and it works
http://plnkr.co/edit/xsCc8rpvDItUG0SPoMyp?p=preview

**Comment by GBora** [comment]
@lordfriend 

True, then I'm a little stumped maybe I'm not using the most up to-date version of the plugin (I installed it with bower) ?

**Comment by lordfriend** [comment]
This feature has not been changed for a long time. I don't think the version matters.

**Comment by GBora** [comment]
@lordfriend  When for example I try to use the translate service in my options it works but no matter what I do it doesn't want to work for title-tpl.

Do you have any ideea on what might cause this behaviour ?

**Comment by lordfriend** [comment]
Sorry, I have no idea..

**Comment by GBora** [comment]
I've updated every bower dependency in the project and it happened to solve this issue, clearly I had some bad weird/dependencies locally and they caused the problem.
